version: "3.8"

services:
    nginx:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        depends_on:
            - php-fpm
        ports:
            - 8080:80
        restart: always

    php-fpm:
        build:
            context: .
            dockerfile: ./docker/php-fpm/Dockerfile
        restart: always
