version: "3.8"

services:
    nginx:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        depends_on:
            - php-fpm
        ports:
            - 8080:80
        volumes:
            - ./:/var/www:rw
        restart: always

    php-fpm:
        build:
            context: .
            dockerfile: ./docker/php-fpm/Dockerfile
        volumes:
            - ./:/var/www:rw
        user: ${UID}:${GID}
        restart: always
